### ISSUE TITLE
400 - Template "default.html.twig" is not defined.

### ISSUE THREAD

**Issue by kwaimind** [vmcosta/grav-skeleton-grayscale-site#1]
When using the theme installer or the command line (`bin/gpm install grayscale`), I get the following error:

400 - Template "default.html.twig" is not defined.

Any ideas?

### Logs
```
[2015-12-12 23:36:54] grav.CRITICAL: Template "default.html.twig" is not defined. - Trace: #0 /Applications/MAMP/htdocs/solo/system/src/Grav/Common/Grav.php(157): Grav\Common\Twig\Twig->processSite(NULL) #1 /Applications/MAMP/htdocs/solo/vendor/pimple/pimple/src/Pimple/Container.php(113): Grav\Common\Grav::Grav\Common\{closure}(Object(Grav\Common\Grav)) #2 /Applications/MAMP/htdocs/solo/system/src/Grav/Common/Grav.php(257): Pimple\Container->offsetGet('output') #3 /Applications/MAMP/htdocs/solo/index.php(37): Grav\Common\Grav->process() #4 {main} [] []
```

**Comment by vmcosta** [comment]
Hi Daniel,
That's strange I've just tried myself and it worked.

```
Preparing to install Grayscale [v1.0.0]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...    ok                             
  '- Success!  
```

**Comment by kwaimind** [comment]
Yes I got that, but when when you run the site in the browser (in my case localhost) you get the 404 error.

**Comment by vmcosta** [comment]
You shouldn't have to download the Theme if you have installed the skeleton package.
Can you try to download and install the [skeleton](https://github.com/vmcosta/grav-skeleton-grayscale-site/releases)?

I assume the error exists because you have a default.md file in your pages and that default.md is searching for a template with the same name (default.html.twig) that of course does not exist.

**Comment by vmcosta** [comment]
@kwaimind I'm going to close this issue for now, let me know in case you need something else.
